import { useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { createTicket } from '../features/supervisor/ticketService'
import type { TicketEvidence, TicketPriority } from '../features/supervisor/ticketTypes'

export default function SupervisorNewTicketPage() {
  const navigate = useNavigate(); const inputRef = useRef<HTMLInputElement>(null); const [category, setCategory] = useState(''); const [priority, setPriority] = useState<TicketPriority | ''>(''); const [description, setDescription] = useState(''); const [evidence, setEvidence] = useState<TicketEvidence[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [drag, setDrag] = useState(false)
  const addFiles = (files: FileList | File[]) => { const accepted = Array.from(files); const invalid = accepted.find((file) => !['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024); if (invalid) { setError('Solo se aceptan JPG, PNG o WebP de hasta 5 MB.'); return } if (evidence.length + accepted.length > 5) { setError('Puedes adjuntar máximo 5 fotografías.'); return } setError(''); setEvidence((current) => [...current, ...accepted.map((file, index) => ({ id: `${file.name}-${Date.now()}-${index}`, name: file.name, type: file.type, url: URL.createObjectURL(file) }))]) }
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!category || !priority || description.trim().length < 10) { setError('Completa categoría, prioridad y una descripción de al menos 10 caracteres.'); return } setSaving(true); const ticket = await createTicket({ category, priority, description: description.trim(), evidence }); setSaving(false); navigate(`/supervisor/tickets/${ticket.id}`) }
  return <section><div className="supervisor-page-heading"><span className="eyebrow">Portal tienda</span><h1>Registrar nueva incidencia</h1><p>Registra y documenta los detalles de la avería de tu tienda.</p></div><form className="ticket-form" onSubmit={submit}><div className="form-grid"><label>Especialidad<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">Seleccione la especialidad...</option><option>Climatización</option><option>Eléctrico</option><option>Plomería</option><option>Refrigeración</option></select></label><label>Prioridad<select value={priority} onChange={(event) => setPriority(event.target.value as TicketPriority)}><option value="">Seleccione prioridad...</option><option>Alta</option><option>Media</option><option>Baja</option></select></label></div><label>Descripción del problema<textarea value={description} maxLength={500} onChange={(event) => setDescription(event.target.value)} placeholder="Describe detalladamente la incidencia..." /><small>{description.length}/500 caracteres</small></label><label>Fotografías de evidencia<div className={`upload-box${drag ? ' upload-box--drag' : ''}`} onDragOver={(event) => { event.preventDefault(); setDrag(true) }} onDragLeave={() => setDrag(false)} onDrop={(event) => { event.preventDefault(); setDrag(false); addFiles(event.dataTransfer.files) }} onClick={() => inputRef.current?.click()}><strong>↑</strong><span>Arrastra fotos o haz clic para subir</span><small>Máx. 5 archivos, JPG, PNG o WebP</small><input ref={inputRef} hidden type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => event.target.files && addFiles(event.target.files)} /></div></label>{evidence.length > 0 && <div className="evidence-grid">{evidence.map((file) => <div key={file.id}><img src={file.url} alt={file.name} /><button type="button" onClick={() => setEvidence((items) => items.filter((item) => item.id !== file.id))}>Eliminar</button></div>)}</div>}{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button-secondary" onClick={() => navigate('/supervisor/tickets')}>Cancelar</button><button type="submit" className="button-primary" disabled={saving}>{saving ? 'Enviando...' : 'Enviar reporte'}</button></div></form></section>
}
