# Generated by Django 5.0.6 on 2026-09-06 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='origen',
            field=models.CharField(choices=[('checklist', 'Checklist mensual (bolsa compartida)'), ('ticket', 'Generada desde un ticket')], default='checklist', max_length=20),
        ),
        migrations.AddField(
            model_name='visita',
            name='ticket_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_generadas', to='core.ticket'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
