# Generated by Django 5.0.6 on 2026-09-28 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visita_origen_visita_ticket_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='core.itemplantilla'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.ticket'),
        ),
        migrations.AddField(
            model_name='itemplantilla',
            name='foto_requerida',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='completada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='descripcion_fallo_ubicacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='distancia_inicio_metros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='excepcion_tiempo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visita',
            name='excepcion_tiempo_aprobada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='excepcion_tiempo_revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excepciones_tiempo_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visita',
            name='iniciada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='justificacion_excepcion_tiempo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='latitud_inicio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='longitud_inicio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='proximidad_inicio_validada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.checklist'),
        ),
    ]
