# Generated by Django 5.2.17 on 2026-10-02 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def audit_existing(apps, schema_editor):
    from django.db.models import Count
    answers = apps.get_model('core', 'RespuestaItem')
    visits = apps.get_model('core', 'Visita')
    duplicates = list(answers.objects.values('checklist_id', 'item_id').annotate(n=Count('id')).filter(n__gt=1))
    tickets = list(visits.objects.filter(origen='ticket', ticket_origen_id__isnull=False).values('ticket_origen_id').annotate(n=Count('id')).filter(n__gt=1))
    if duplicates or tickets:
        raise RuntimeError(f'Migración detenida: respuestas duplicadas={duplicates}; tickets con varias visitas={tickets}. Se requiere una decisión; no se borra historial.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visita_origen_visita_ticket_origen_and_more'),
    ]

    operations = [
        migrations.RunPython(audit_existing, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('datos', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Excepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('time_limit', 'Tiempo'), ('location', 'GPS')], max_length=20)),
                ('motivo', models.TextField()),
                ('fallo', models.CharField(blank=True, max_length=50)),
                ('solicitada_en', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=10)),
                ('revisada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_decision', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=200)),
                ('huella', models.CharField(max_length=64)),
                ('respuesta', models.JSONField(null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='plantilla_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='tareas_snapshot',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='capturada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='client_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='eliminada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.itemplantilla'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='origen',
            field=models.CharField(choices=[('camera', 'Cámara'), ('gallery', 'Galería'), ('upload', 'Archivo')], default='upload', max_length=10),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='tamano',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivos', to='core.ticket'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivos', to='core.visita'),
        ),
        migrations.AddField(
            model_name='itemplantilla',
            name='foto_obligatoria',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reasignacionticket',
            name='fecha_anterior',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reasignacionticket',
            name='fecha_nueva',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reasignacionticket',
            name='motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reasignacionticket',
            name='urgencia_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_salientes', to='core.nivelurgencia'),
        ),
        migrations.AddField(
            model_name='reasignacionticket',
            name='urgencia_nueva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_entrantes', to='core.nivelurgencia'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cerrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tienda',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='contacto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='auth_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visita',
            name='borrador_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visita',
            name='completado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.contrato'),
        ),
        migrations.AddField(
            model_name='visita',
            name='cuota',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='visita',
            name='descripcion_trabajo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='enviado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='formulario_abierto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='formulario_vence_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='iniciado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='periodo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='radio_metros',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='tienda_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='visita',
            name='ubicacion_cierre',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='ubicacion_inicio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='core.checklist'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.tienda'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiendas', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='ticket_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_generadas', to='core.ticket'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='core.tienda'),
        ),
        migrations.AddConstraint(
            model_name='respuestaitem',
            constraint=models.UniqueConstraint(fields=('checklist', 'item'), name='respuesta_checklist_item_unica'),
        ),
        migrations.AddConstraint(
            model_name='visita',
            constraint=models.UniqueConstraint(condition=models.Q(('origen', 'checklist'), ('periodo__isnull', False)), fields=('tienda', 'periodo', 'cuota'), name='visita_cuota_mensual_unica'),
        ),
        migrations.AddConstraint(
            model_name='visita',
            constraint=models.UniqueConstraint(condition=models.Q(('origen', 'ticket'), ('ticket_origen__isnull', False), ('vigente', True)), fields=('ticket_origen',), name='ticket_una_visita_vigente'),
        ),
        migrations.AddField(
            model_name='evento',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='core.ticket'),
        ),
        migrations.AddField(
            model_name='evento',
            name='visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='core.visita'),
        ),
        migrations.AddField(
            model_name='excepcion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excepciones_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excepcion',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_excepcion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excepcion',
            name='visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excepciones', to='core.visita'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='excepcion',
            constraint=models.UniqueConstraint(fields=('visita', 'tipo'), name='visita_tipo_excepcion_unica'),
        ),
        migrations.AddConstraint(
            model_name='operacion',
            constraint=models.UniqueConstraint(fields=('usuario', 'clave'), name='operacion_idempotente_unica'),
        ),
    ]
