# Generated by Django 5.0.6 on 2026-09-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evidencia_item_evidencia_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asignado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_inicializada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visita',
            name='comentario_revision_tiempo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='comentario_revision_ubicacion',
            field=models.TextField(blank=True),
        ),
    ]
