# Generated by Django 5.2.17 on 2026-10-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_evidencia_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('programado', 'Programado'), ('en_proceso', 'En proceso'), ('pendiente_validacion', 'Pendiente de revisión'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20),
        ),
    ]
