# Generated by Django 5.2.17 on 2026-10-02 02:54

import uuid
from django.db import migrations, models


def identify_files(apps, schema_editor):
    Evidencia = apps.get_model('core', 'Evidencia')
    for evidence in Evidencia.objects.filter(client_id__isnull=True).iterator():
        evidence.client_id = uuid.uuid4()
        evidence.save(update_fields=['client_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_evento_excepcion_operacion_and_more'),
    ]

    operations = [
        migrations.RunPython(identify_files, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='evidencia',
            name='client_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
