# Generated by Django 5.2.17 on 2026-10-02 04:24

import datetime
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


def audit_timestamps(apps, schema_editor):
    invalid = []
    for visit in apps.get_model('core', 'Visita').objects.using(schema_editor.connection.alias).iterator():
        opened, deadline, started = visit.formulario_abierto_en, visit.formulario_vence_en, visit.iniciado_en
        if (opened or deadline) and (not opened or not deadline or not started or opened < started or deadline != opened + datetime.timedelta(minutes=5)):
            invalid.append(visit.pk)
        elif visit.enviado_en and (not opened or visit.enviado_en < opened):
            invalid.append(visit.pk)
        elif visit.completado_en and (not visit.enviado_en or visit.completado_en < visit.enviado_en):
            invalid.append(visit.pk)
    if invalid:
        raise RuntimeError(f'Timestamps inconsistentes en visitas {invalid[:100]}. No se modificó el historial; requiere decisión antes de migrar.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ticket_estado'),
    ]

    operations = [
        migrations.RunPython(audit_timestamps, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reasignacionticket',
            name='reasignado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reasignacionticket',
            name='tecnico_anterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones_salientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reasignacionticket',
            name='tecnico_nuevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones_entrantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reasignacionticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones', to='core.ticket'),
        ),
        migrations.AddConstraint(
            model_name='visita',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('formulario_abierto_en__isnull', True), ('formulario_vence_en__isnull', True)), models.Q(('formulario_abierto_en__gte', models.F('iniciado_en')), ('formulario_abierto_en__isnull', False), ('formulario_vence_en', django.db.models.expressions.CombinedExpression(models.F('formulario_abierto_en'), '+', models.Value(datetime.timedelta(seconds=300)))), ('formulario_vence_en__isnull', False), ('iniciado_en__isnull', False)), _connector='OR'), name='visita_formulario_plazo_original'),
        ),
        migrations.AddConstraint(
            model_name='visita',
            constraint=models.CheckConstraint(condition=models.Q(('enviado_en__isnull', True), models.Q(('enviado_en__gte', models.F('formulario_abierto_en')), ('formulario_abierto_en__isnull', False)), _connector='OR'), name='visita_envio_despues_apertura'),
        ),
        migrations.AddConstraint(
            model_name='visita',
            constraint=models.CheckConstraint(condition=models.Q(('completado_en__isnull', True), models.Q(('completado_en__gte', models.F('enviado_en')), ('enviado_en__isnull', False)), _connector='OR'), name='visita_finalizacion_despues_envio'),
        ),
    ]
