# Generated by Django 5.2.17 on 2026-10-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ticket_tecnico_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excepcion',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Pendiente'), ('programado', 'Pendiente'), ('en_proceso', 'En proceso'), ('pendiente_validacion', 'En revisión'), ('resuelto', 'Finalizado'), ('cerrado', 'Finalizado')], default='abierto', max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Pendiente'), ('en_curso', 'En proceso'), ('completada', 'Finalizado'), ('pendiente_validacion', 'En revisión'), ('no_realizada', 'No realizada')], default='programada', max_length=20),
        ),
    ]
