# Generated by Django 5.2.17 on 2026-10-02 23:01

import datetime
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


def recover_recorded_claims(apps, schema_editor):
    # Solo eventos reales del propietario actual; no inventa horas para registros sin evidencia.
    Visit = apps.get_model('core', 'Visita')
    Event = apps.get_model('core', 'Evento')
    alias = schema_editor.connection.alias
    for visit in Visit.objects.using(alias).filter(origen='checklist', vigente=True, estado='programada',
            tecnico__isnull=False, iniciado_en__isnull=True, formulario_abierto_en__isnull=True):
        claim = Event.objects.using(alias).filter(visita_id=visit.pk, tipo='claim').order_by('-fecha', '-pk').first()
        if claim and claim.actor_id == visit.tecnico_id:
            Visit.objects.using(alias).filter(pk=visit.pk).update(
                reclamada_en=claim.fecha, reclamo_vence_en=claim.fecha + datetime.timedelta(hours=2))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_excepcion_revision_alter_ticket_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='reclamada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='reclamo_vence_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(recover_recorded_claims, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('actor__isnull', False), models.Q(('ticket__isnull', True), ('tipo', 'claim_release'), ('visita__isnull', False)), _connector='OR'), name='evento_actor_o_liberacion_sistema'),
        ),
        migrations.AddConstraint(
            model_name='visita',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reclamada_en__isnull', True), ('reclamo_vence_en__isnull', True)), models.Q(('origen', 'checklist'), ('reclamada_en__isnull', False), ('reclamo_vence_en', django.db.models.expressions.CombinedExpression(models.F('reclamada_en'), '+', models.Value(datetime.timedelta(seconds=7200)))), ('reclamo_vence_en__isnull', False)), _connector='OR'), name='visita_reclamo_dos_horas'),
        ),
    ]
