# Generated by Django 5.2.17 on 2026-10-02 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reasignacionticket_reasignado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visita',
            name='excepcion_revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excepciones_revisadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
