# Generated by Django 5.2.17 on 2026-10-03 00:35

import django.core.validators
from django.db import migrations, models


def audit_minimum(apps, schema_editor):
    Contract = apps.get_model('core', 'Contrato')
    ids = list(Contract.objects.using(schema_editor.connection.alias).filter(
        minimo_intervenciones_mensual__lt=2).values_list('pk', flat=True))
    if ids:
        raise RuntimeError(f'Contratos con mínimo inferior a dos por tienda: {ids}. No se modifica historial automáticamente.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_visita_reclamada_en_visita_reclamo_vence_en_and_more'),
    ]

    operations = [
        migrations.RunPython(audit_minimum, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contrato',
            name='minimo_intervenciones_mensual',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('minimo_intervenciones_mensual__gte', 2)), name='contrato_minimo_dos_por_tienda'),
        ),
    ]
