# Generated by Django 5.2.17 on 2026-10-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_visita_minimo_mensual_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
