# Generated by Django 5.2.17 on 2026-10-03 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cliente_nombre_comercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_comercial',
        ),
    ]
