# Generated by Django 5.2.17 on 2026-10-03 00:42

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGistExtension


def audit_contracts(apps, schema_editor):
    Contract = apps.get_model('core', 'Contrato')
    contracts = list(Contract.objects.using(schema_editor.connection.alias).order_by('cliente_id', 'pk'))
    invalid = [c.pk for c in contracts if c.fecha_fin and c.fecha_fin < c.fecha_inicio]
    overlaps = []
    for index, first in enumerate(contracts):
        if not first.activo:
            continue
        for second in contracts[index+1:]:
            if first.cliente_id == second.cliente_id and second.activo and \
                    (not first.fecha_fin or second.fecha_inicio <= first.fecha_fin) and \
                    (not second.fecha_fin or first.fecha_inicio <= second.fecha_fin):
                overlaps.append((first.pk, second.pk))
    if invalid or overlaps:
        raise RuntimeError(f'Contratos con fechas inválidas: {invalid}; superpuestos: {overlaps}. Revisar sin borrar ni fusionar historial.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contrato_minimo_intervenciones_mensual_and_more'),
    ]

    operations = [
        migrations.RunPython(audit_contracts, migrations.RunPython.noop),
        BtreeGistExtension(),
        migrations.AddField(
            model_name='visita',
            name='minimo_mensual_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='contrato_fechas_ordenadas'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('activo', True)), expressions=[('cliente', '='), (models.Func('fecha_inicio', 'fecha_fin', models.Value('[]'), function='DATERANGE', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='contrato_activo_sin_superposicion'),
        ),
    ]
