# Generated by Django 5.2.17 on 2026-10-05 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_legacy_duplicate_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CoberturaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coberturas_usuario', to='core.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coberturas', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coberturas', to='core.zona')),
            ],
        ),
        migrations.AddField(
            model_name='tienda',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiendas', to='core.zona'),
        ),
        migrations.CreateModel(
            name='ClienteEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('habilitada_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_habilitados', to='core.categoriaproblema')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especialidades', to='core.cliente')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'activo'], name='cliente_espec_activo_idx')],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'categoria'), name='cliente_especialidad_unica')],
            },
        ),
        migrations.AddIndex(
            model_name='zona',
            index=models.Index(fields=['cliente', 'activo'], name='zona_cliente_activo_idx'),
        ),
        migrations.AddConstraint(
            model_name='zona',
            constraint=models.UniqueConstraint(fields=('cliente', 'nombre'), name='zona_cliente_nombre_unico'),
        ),
        migrations.AddIndex(
            model_name='coberturausuario',
            index=models.Index(fields=['usuario', 'activo'], name='cobertura_usuario_activo_idx'),
        ),
        migrations.AddConstraint(
            model_name='coberturausuario',
            constraint=models.UniqueConstraint(fields=('usuario', 'cliente', 'zona'), name='cobertura_usuario_cliente_zona_unica'),
        ),
    ]
