# Generated by Django 5.2.17 on 2026-10-06 02:49

import django.db.models.deletion
from django.db import migrations, models


def check_active_executions(apps, schema_editor):
    visits = apps.get_model('core', 'Visita').objects.using(schema_editor.connection.alias)
    active = visits.filter(tecnico_id__isnull=False, iniciado_en__isnull=False,
                           enviado_en__isnull=True, estado__in=['en_curso', 'pendiente_validacion'])
    duplicates = list(active.values('tecnico_id').annotate(total=models.Count('pk')).filter(total__gt=1))
    if duplicates:
        details = {row['tecnico_id']: list(active.filter(tecnico_id=row['tecnico_id']).values_list('pk', flat=True))
                   for row in duplicates}
        raise RuntimeError('0018: ejecuciones activas legacy incompatibles. Requieren revisión auditada; '
                           'no se elige ni termina ninguna automáticamente. Técnico -> visitas: ' + str(details))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_zona_cobertura_usuario_cliente_especialidad'),
    ]

    operations = [
        migrations.RunPython(check_active_executions, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='excepcion',
            name='visita_tipo_excepcion_unica',
        ),
        migrations.RemoveConstraint(
            model_name='visita',
            name='visita_cuota_mensual_unica',
        ),
        migrations.AddField(
            model_name='excepcion',
            name='scope',
            field=models.CharField(choices=[('arrival', 'Llegada'), ('closure', 'Cierre'), ('form', 'Formulario'), ('legacy', 'Origen no registrado')], default='legacy', max_length=10),
        ),
        migrations.AddField(
            model_name='excepcion',
            name='telemetria',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='intento_anterior',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siguiente_intento', to='core.visita'),
        ),
        migrations.AddField(
            model_name='visita',
            name='no_realizada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='terminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaitem',
            name='resultado',
            field=models.CharField(choices=[('ok', 'Conforme'), ('observado', 'No conforme'), ('no_aplica', 'No aplica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Pendiente'), ('programado', 'Pendiente'), ('en_proceso', 'En proceso'), ('pendiente_validacion', 'En revisión'), ('correccion_requerida', 'Corrección requerida'), ('resuelto', 'Finalizado'), ('cerrado', 'Finalizado')], default='abierto', max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Pendiente'), ('en_curso', 'En proceso'), ('completada', 'Finalizado'), ('pendiente_validacion', 'En revisión'), ('correccion_requerida', 'Corrección requerida'), ('no_realizada', 'No realizada')], default='programada', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='excepcion',
            constraint=models.UniqueConstraint(fields=('visita', 'tipo', 'scope'), name='visita_tipo_scope_excepcion_unica'),
        ),
        migrations.AddConstraint(
            model_name='excepcion',
            constraint=models.CheckConstraint(condition=models.Q(('scope', 'legacy'), models.Q(('scope__in', ['arrival', 'closure']), ('tipo', 'location')), models.Q(('scope', 'form'), ('tipo', 'time_limit')), _connector='OR'), name='excepcion_scope_corresponde_tipo'),
        ),
        migrations.AddConstraint(
            model_name='visita',
            constraint=models.UniqueConstraint(condition=models.Q(('origen', 'checklist'), ('periodo__isnull', False), ('vigente', True)), fields=('tienda', 'periodo', 'cuota'), name='visita_cuota_mensual_unica'),
        ),
        migrations.AddConstraint(
            model_name='visita',
            constraint=models.UniqueConstraint(condition=models.Q(('enviado_en__isnull', True), ('estado__in', ['en_curso', 'pendiente_validacion']), ('iniciado_en__isnull', False), ('tecnico__isnull', False)), fields=('tecnico',), name='tecnico_una_ejecucion_activa'),
        ),
        migrations.AddConstraint(
            model_name='visita',
            constraint=models.CheckConstraint(condition=models.Q(('terminado_en__isnull', True), models.Q(('iniciado_en__isnull', False), ('terminado_en__gte', models.F('iniciado_en'))), _connector='OR'), name='visita_fin_fisico_despues_inicio'),
        ),
        migrations.AddConstraint(
            model_name='visita',
            constraint=models.CheckConstraint(condition=models.Q(('terminado_en__isnull', True), ('formulario_abierto_en__isnull', True), ('formulario_abierto_en__gte', models.F('terminado_en')), _connector='OR'), name='visita_formulario_despues_fin'),
        ),
    ]
