# Generated by Django 5.2.17 on 2026-10-08 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_operational_v2"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="visita",
            name="visita_formulario_plazo_original",
        ),
        migrations.AddField(
            model_name="evidencia",
            name="excepcion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidencias",
                to="core.excepcion",
            ),
        ),
        migrations.AddField(
            model_name="evidencia",
            name="proposito",
            field=models.CharField(
                choices=[("result", "Resultado"), ("arrival", "Llegada")],
                default="result",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="visita",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("formulario_abierto_en__isnull", True),
                        ("formulario_vence_en__isnull", True),
                    ),
                    models.Q(
                        ("formulario_abierto_en__gte", models.F("iniciado_en")),
                        ("formulario_abierto_en__isnull", False),
                        ("iniciado_en__isnull", False),
                        models.Q(
                            ("formulario_vence_en__isnull", True),
                            (
                                "formulario_vence_en__gte",
                                models.F("formulario_abierto_en"),
                            ),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="visita_formulario_cronologia",
            ),
        ),
    ]
